CREATE TABLE expenses (
    expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    description VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    receipt_url VARCHAR(500),
    status VARCHAR(30) NOT NULL, -- Pending, Manager_Approved, Finance_Approved ou Rejected
    
    -- Valores Financeiros
    amount NUMERIC(19, 2) NOT NULL,
    fk_currency_id BIGINT NOT NULL REFERENCES currencies(currency_id),
	
    exchange_rate_snapshot NUMERIC(19, 6) NOT NULL DEFAULT 1.0, -- Taxa exata no momento da transação
    
    fk_employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    fk_category_id BIGINT NOT NULL REFERENCES categories(category_id),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);