CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    name VARCHAR(150) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL, -- Employee, Manager ou Finance
    
    fk_department_id BIGINT REFERENCES departments(department_id),
    fk_manager_id BIGINT REFERENCES employees(employee_id), 
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT chk_cpf_len CHECK (LENGTH(cpf) = 3)
);