CREATE TABLE expense_logs (
    expense_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_log_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    action VARCHAR(50) NOT NULL, -- Created, Approved, Rejected ou Updated
    comments TEXT, -- Motivo da rejeição ou observação
    
    fk_expense_id BIGINT NOT NULL REFERENCES expenses(expense_id),
    fk_employee_id BIGINT REFERENCES employees(employee_id), -- Quem fez a ação
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);