CREATE TABLE alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    message VARCHAR(255) NOT NULL,
    severity VARCHAR(20) DEFAULT 'WARNING',
    status VARCHAR(20) DEFAULT 'NEW', -- New ou Resolved
	type VARCHAR(20), -- Category ou Department
    
    fk_expense_id BIGINT REFERENCES expenses(expense_id),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
