CREATE TABLE currencies (
    currency_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    code VARCHAR(3) NOT NULL UNIQUE, -- USD, BRL, ...
    name VARCHAR(50) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_currency_code_len CHECK (LENGTH(code) = 3)
);