CREATE TABLE currency_rates (
    currency_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_rate_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    fk_currency_id BIGINT NOT NULL REFERENCES currencies(currency_id),
    rate NUMERIC(19, 6) NOT NULL, -- Taxa de conversão em relação à moeda base
    valid_date DATE NOT NULL, -- Dia da cotação
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_currency_date UNIQUE (fk_currency_id, valid_date) -- Uma cotação por dia
);