CREATE TABLE currency_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    currency_id BIGINT NOT NULL REFERENCES currencies(id),
    rate NUMERIC(19, 6) NOT NULL, -- Taxa de conversão em relação à moeda base
    valid_date DATE NOT NULL, -- Dia da cotação
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_currency_date UNIQUE (currency_id, valid_date) -- Uma cotação por dia
);