CREATE TABLE departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    name VARCHAR(100) NOT NULL,
    monthly_budget NUMERIC(19, 2) NOT NULL,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);