CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    name VARCHAR(50) NOT NULL,
    daily_limit NUMERIC(19, 2),   
    monthly_limit NUMERIC(19, 2),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
