CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    
    name VARCHAR(50) NOT NULL,
    daily_limit NUMERIC(19, 2),   
    monthly_limit NUMERIC(19, 2),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
