CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    description VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    receipt_url VARCHAR(500),
    status VARCHAR(30) NOT NULL, -- Pending, Manager_Approved, Finance_Approved ou Rejected
    
    -- Valores Financeiros
    amount NUMERIC(19, 2) NOT NULL,
    currency_id BIGINT NOT NULL REFERENCES currencies(id),
	
    exchange_rate_snapshot NUMERIC(19, 6) NOT NULL DEFAULT 1.0, -- Taxa exata no momento da transação
    
    employee_id BIGINT NOT NULL REFERENCES employees(id),
    category_id BIGINT NOT NULL REFERENCES categories(id),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);