CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    name VARCHAR(150) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL, -- Employee, Manager ou Finance
    
    department_id BIGINT REFERENCES departments(id),
    manager_id BIGINT REFERENCES employees(id),
    user_id BIGINT UNIQUE REFERENCES users(id), -- FK para User

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT chk_cpf_len CHECK (LENGTH(cpf) = 11)
);