CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    message VARCHAR(255) NOT NULL,
    severity VARCHAR(20) DEFAULT 'WARNING',
    status VARCHAR(20) DEFAULT 'NEW', -- New ou Resolved
	type VARCHAR(20), -- Category ou Department
    
    expense_id BIGINT REFERENCES expenses(id),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
