CREATE TABLE expense_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    action VARCHAR(50) NOT NULL, -- Created, Approved, Rejected ou Updated
    comments TEXT, -- Motivo da rejeição ou observação
    
    expense_id BIGINT NOT NULL REFERENCES expenses(id),
    employee_id BIGINT REFERENCES employees(id), -- Quem fez a ação
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);